### ISSUE TITLE
Add requirements.txt file

### ISSUE THREAD

**Issue by Raghvender1205** [Karan-Choudhary/AVmod#1]
Add the module and libraries used and a readme file on how to install those libraries.

Like, a requirements.txt file has all the libraries in it. To install it use the command.
```
pip install -r requirements.txt
```

**Comment by Karan-Choudhary** [comment]
Sure

**Comment by Karan-Choudhary** [comment]
[requirements.txt](https://github.com/Karan-Choudhary/AVmod/blob/main/requirements.txt) added

**Comment by Raghvender1205** [comment]
Nice
